paths-ignore:
  - "prometheus-docker-compose.yaml" # because it is a prototype and we don't care about grafana secret
  - "02-GoldenSignals/docker-compose.yaml" # because it is a prototype and we don't care about grafana secret
