version: "3"

# volumes:
#   prometheus-data:
#   grafana-data:

services:
  api:
    network_mode: host
    build: .
    volumes:
      - logs-data:/app/logs
    # ports:
    #   - "5000:5000"
    #   - "8000:8000"
    # environment:
    #   - OTEL_RESOURCE_ATTRIBUTES=service.name=slow-api
    #   - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
    #   - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
    #   - OTEL_METRICS_EXPORTER=prometheus

  fluentbit:
    # image: cr.fluentbit.io/fluent/fluent-bit:2.2.0
    image: fluent/fluent-bit
    container_name: fluentbit
    network_mode: host
    volumes:
      - logs-data:/logs
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit.parsers.conf:/fluent-bit/etc/fluent-bit.parsers.conf
    depends_on:
      - opensearch
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]


  # prometheus:
  #   image: prom/prometheus
  #   network_mode: host
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   # ports:
  #   #   - "9090:9090"

  # grafana:
  #   image: grafana/grafana
  #   network_mode: host
  #   # ports:
  #   #   - "3000:3000"
  #   depends_on:
  #     - prometheus
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=grafana
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #     - ./grafana-provisioning:/etc/grafana/provisioning      

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   network_mode: host
  #   # ports:
  #   #   - "16686:16686" # UI Web
  #   #   # - "6831:6831/udp"
  #   #   - "4317:4317"    # OTLP (nouveau protocole)


  opensearch:
    image: opensearchproject/opensearch:2.5.0
    network_mode: host
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      # - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # ports:
    #   - 9200:9200
    #   - 9600:9600
    volumes:
      - opensearch-data:/usr/share/opensearch/data
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    network_mode: host
    container_name: opensearch-dashboards
    # ports:
    #   - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=["https://localhost:9200"]

volumes:
  opensearch-data:
  logs-data: