[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File fluent-bit.parsers.conf

[INPUT]
    Name   tail
    Path   /logs/app.log
    Parser json
    Tag    app.logs

[OUTPUT]
    Name  opensearch
    Match app.logs
    Host  127.0.0.1
    Port  9200
    Index logs-flask
    # Type  _doc
    Logstash_Format On
    HTTP_User  admin
    HTTP_Passwd admin
    tls  On
    tls.verify  Off
    # AWS_Auth  Off
    # tls.debug 4
    # tls.version TLSv1.2  # Ou TLSv1.3 selon OpenSearch    
    # trace_output On