volumes:
  # prometheus-data:
  grafana-data:

services:
  api:
    network_mode: host
    build: .
    # ports:
    #   - "5000:5000"
    #   - "8000:8000"

  prometheus:
    image: prom/prometheus:v3.1.0
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.size=1GB"
    # ports:
    #   - "9090:9090"

  grafana:
    image: grafana/grafana
    network_mode: host
    # ports:
    #   - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning

