[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name         tail
    Path         /logs/api/*.log,/logs/worker/*.log,/logs/frontend/*.log
    Parser       json
    Tag          demoboard.logs
    Refresh_Interval 2

[OUTPUT]
    Name         opensearch
    Match        demoboard.logs
    Host         opensearch
    Port         9200
    Index        demoboard-logs
    Logstash_Format On
    Logstash_Prefix demoboard-logs
    Suppress_Type_Name On
    HTTP_User    admin
    HTTP_Passwd  Str0ng!DemoBoard#2026
    tls          On
    tls.verify   Off
