server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://lgtm:3100/loki/api/v1/push

scrape_configs:
  - job_name: demoboard-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: demoboard-api
          service_name: demoboard-api
          __path__: /var/log/demoboard/api/*.log

  - job_name: demoboard-worker
    static_configs:
      - targets:
          - localhost
        labels:
          job: demoboard-worker
          service_name: demoboard-worker
          __path__: /var/log/demoboard/worker/*.log

  - job_name: demoboard-frontend
    static_configs:
      - targets:
          - localhost
        labels:
          job: demoboard-frontend
          service_name: demoboard-frontend
          __path__: /var/log/demoboard/frontend/*.log
